import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { Header } from "@/modules/layout/header/header";

const inter = Inter({
	variable: "--font-inter",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
			<body
				className={cn(
					inter.variable,
					"flex min-h-dvh flex-col font-inter antialiased",
				)}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}

export default RootLayout;
